package com.mana.pojo;

import java.io.Serializable;

public class Usertask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.taskid
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.schedule
     *
     * @mbggenerated
     */
    private String schedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usertask
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.taskid
     *
     * @return the value of usertask.taskid
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.taskid
     *
     * @param taskid the value for usertask.taskid
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.userid
     *
     * @return the value of usertask.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.userid
     *
     * @param userid the value for usertask.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.title
     *
     * @return the value of usertask.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.title
     *
     * @param title the value for usertask.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.content
     *
     * @return the value of usertask.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.content
     *
     * @param content the value for usertask.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.time
     *
     * @return the value of usertask.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.time
     *
     * @param time the value for usertask.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.schedule
     *
     * @return the value of usertask.schedule
     *
     * @mbggenerated
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.schedule
     *
     * @param schedule the value for usertask.schedule
     *
     * @mbggenerated
     */
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }

	
}