package com.mana.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.mana.pojo.Usertask;

@Component
@Mapper
public interface UsertaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbggenerated
     */
    void delete(String taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbggenerated
     */
    boolean insert(Usertask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbggenerated
     */
    int insertSelective(Usertask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbggenerated
     */
    Usertask selectByPrimaryKey(String taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Usertask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbggenerated
     */
    void updateByPrimaryKey(Usertask record);

	List<Usertask> selectByUserId(String userid);

	List<Usertask> getAllTask();
}